---
apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  type: NodePort
  selector:
    app: deploy1
  ports:
    - name: nginx-http
      port: 9001
      nodePort: 30000
      protocol: TCP
      targetPort: 80
