---
apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: deploy1
  ports:
    - name: nginx-http
      port: 9001
      protocol: TCP
      targetPort: 80
    - name: multitool-http
      port: 9002
      protocol: TCP
      targetPort: 8080
